import { app, BrowserWindow, Menu, ipcMain, clipboard, dialog } from 'electron';
import { ZipManager } from './main/zip/ZipManager';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 1100,
    minWidth: 1100,
    minHeight: 600,
    backgroundColor: '#1E1E2F',
    titleBarStyle: process.platform === 'darwin' ? 'hiddenInset' : 'hidden',
    ...(process.platform === 'darwin' ? { trafficLightPosition: { x: 12, y: 12 } } : {}),
    ...(process.platform !== 'darwin'
      ? { titleBarOverlay: { color: '#1c1c1c', symbolColor: '#e4e4e4', height: 36 } }
      : {}),
    autoHideMenuBar: true,
    icon: require('path').join(__dirname, '../src/assets/app-icons/icon.ico'),
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      sandbox: true,
    },
  });

  // Remove the default application menu (File/Edit/View/Window/Help)
  Menu.setApplicationMenu(null);
  mainWindow.setMenuBarVisibility(false);

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools in development only.
  if (!app.isPackaged) {
    mainWindow.webContents.openDevTools({ mode: 'detach' });
  }

  ipcMain.on('app:copy', (_evt, text: string) => clipboard.writeText(String(text || '')));

  const manager = new ZipManager();
  ipcMain.handle('zip:open', async () => {
    const res = await dialog.showOpenDialog(mainWindow, {
      filters: [{ name: 'Archives', extensions: ['zip', 'biz'] }],
      properties: ['openFile'],
    });
    if (res.canceled || res.filePaths.length === 0) return null;
    const filePath = res.filePaths[0];
    await manager.close();
    const { root, summary, title } = await manager.open(filePath);
    return { tree: root, summary, title };
  });
  ipcMain.handle('zip:openPath', async (_evt, fileOrBuffer: any) => {
    await manager.close();
    if (typeof fileOrBuffer === 'string') {
      const { root, summary, title } = await manager.open(fileOrBuffer);
      return { tree: root, summary, title };
    }
    if (fileOrBuffer && fileOrBuffer.path) {
      const { root, summary, title } = await manager.open(fileOrBuffer.path as string);
      return { tree: root, summary, title };
    }
    if (fileOrBuffer && fileOrBuffer.data) {
      const buf = Buffer.from(fileOrBuffer.data);
      const { root, summary, title } = await manager.openBuffer(buf, fileOrBuffer.name);
      return { tree: root, summary, title };
    }
    throw new Error('Invalid argument to zip:openPath');
  });
  ipcMain.handle('zip:close', async () => {
    await manager.close();
    return true;
  });
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
